if(MSVC)
    if(${BUILD_LOCAL})
        find_path(
            TBB_SRC
            NAMES
            Makefile
        )
        if(NOT EXISTS ${TBB_SRC}/Makefile)
            message(FATAL_ERROR "Cannot find TBB Source Path")
        endif()
        ExternalProject_Add(
            TBB
            TMP_DIR
            ${CMAKE_BINARY_DIR}/tmp
            STAMP_DIR
            ${CMAKE_BINARY_DIR}/stamp
            DOWNLOAD_DIR
            ${CMAKE_BINARY_DIR}
            SOURCE_DIR
            ${CMAKE_BINARY_DIR}/TBB
            BINARY_DIR
            ${CMAKE_BINARY_DIR}/TBB-build
            INSTALL_DIR
            ${CMAKE_BINARY_DIR}/TBB-install
            DOWNLOAD_COMMAND 
            ${CMAKE_COMMAND} -E copy_directory ${TBB_SRC} ${CMAKE_BINARY_DIR}/TBB
            CONFIGURE_COMMAND
            ""
            BUILD_COMMAND
            ""
            INSTALL_COMMAND
            ""
        )
    else()
        ExternalProject_Add(
            TBB
            TMP_DIR
            ${CMAKE_BINARY_DIR}/tmp
            STAMP_DIR
            ${CMAKE_BINARY_DIR}/stamp
            DOWNLOAD_DIR
            ${CMAKE_BINARY_DIR}
            SOURCE_DIR
            ${CMAKE_BINARY_DIR}/TBB
            BINARY_DIR
            ${CMAKE_BINARY_DIR}/TBB-build
            INSTALL_DIR
            ${CMAKE_BINARY_DIR}/TBB-install
            GIT_REPOSITORY
            "https://github.com/01org/tbb.git"
            GIT_TAG
            "2018_U5"
            CONFIGURE_COMMAND
            ""
            BUILD_COMMAND
            ""
            INSTALL_COMMAND
            ""
        )
    endif()
    ExternalProject_Add_Step(
        TBB
        release_build
        COMMAND
        "${CMAKE_MAKE_PROGRAM}"
        "/m"
        "/p:Configuration=Release"
        "/p:Platform=X64"
        "/p:PlatformToolset=v140"
        "${CMAKE_BINARY_DIR}/TBB/build/vs2013/makefile.sln"
        DEPENDEES
        build
    )
    ExternalProject_Add_Step(
        TBB
        debug_build
        COMMAND
        "${CMAKE_MAKE_PROGRAM}"
        "/m"
        "/p:Configuration=Debug"
        "/p:Platform=X64"
        "/p:PlatformToolset=v140"
        "${CMAKE_BINARY_DIR}/TBB/build/vs2013/makefile.sln"
        DEPENDEES
        build
    )
    set(TBB_LIBRARY_DEBUG:FILEPATH ${CMAKE_BINARY_DIR}/TBB-build/bin/Debug/tbb_debug.lib)
TBB_LIBRARY_RELEASE:FILEPATH=C:/ccode/QvtkProject_build/TBB/build/vs2013/x64/Debug/tbb_debug.pdb
TBB_MALLOC_LIBRARY_DEBUG:FILEPATH=TBB_MALLOC_LIBRARY_DEBUG-NOTFOUND
TBB_MALLOC_LIBRARY_RELEASE:FILEPATH=TBB_MALLOC_LIBRARY_RELEASE-NOTFOUND
TBB_MALLOC_PROXY_LIBRARY_DEBUG:FILEPATH=TBB_MALLOC_PROXY_LIBRARY_DEBUG-NOTFOUND
TBB_MALLOC_PROXY_LIBRARY_RELEASE:FILEPATH=TBB_MALLOC_PROXY_LIBRARY_RELEASE-NOTFOUND
else()
    if(${BUILD_LOCAL})
        find_path(
            TBB_SRC
            NAMES
            Makefile
        )
        if(NOT EXISTS ${TBB_SRC}/Makefile)
            message(FATAL_ERROR "Cannot find TBB Source Path")
        endif()
        ExternalProject_Add(
            TBB
            TMP_DIR
            ${CMAKE_BINARY_DIR}/tmp
            STAMP_DIR
            ${CMAKE_BINARY_DIR}/stamp
            DOWNLOAD_DIR
            ${CMAKE_BINARY_DIR}
            SOURCE_DIR
            ${CMAKE_BINARY_DIR}/TBB
            BINARY_DIR
            ${CMAKE_BINARY_DIR}/TBB-build
            INSTALL_DIR
            ${CMAKE_BINARY_DIR}/TBB-install
            DOWNLOAD_COMMAND 
            ${CMAKE_COMMAND} -E copy_directory ${TBB_SRC} ${CMAKE_BINARY_DIR}/TBB
            CONFIGURE_COMMAND
            ""
            BUILD_COMMAND
            "${CMAKE_MAKE_PROGRAM}"
            "-j"
            "-C"
            "${CMAKE_BINARY_DIR}/TBB"
            INSTALL_COMMAND
            ""
        )
    else()
        ExternalProject_Add(
            TBB
            TMP_DIR
            ${CMAKE_BINARY_DIR}/tmp
            STAMP_DIR
            ${CMAKE_BINARY_DIR}/stamp
            DOWNLOAD_DIR
            ${CMAKE_BINARY_DIR}
            SOURCE_DIR
            ${CMAKE_BINARY_DIR}/TBB
            BINARY_DIR
            ${CMAKE_BINARY_DIR}/TBB-build
            INSTALL_DIR
            ${CMAKE_BINARY_DIR}/TBB-install
            GIT_REPOSITORY
            "https://github.com/01org/tbb.git"
            GIT_TAG
            "2018_U5"
            CONFIGURE_COMMAND
            ""
            BUILD_COMMAND
            "${CMAKE_MAKE_PROGRAM}"
            "-j"
            "-C"
            "${CMAKE_BINARY_DIR}/TBB"
            INSTALL_COMMAND
            ""
        )
    endif()
endif()
ExternalProject_Add_Step(
    TBB
    build_copy
    COMMAND
    ${CMAKE_COMMAND}
    -DTBB:PATH=${CMAKE_BINARY_DIR}/TBB
    -DTBB_BUILD:PATH=${CMAKE_BINARY_DIR}/TBB-build
    -P
    ${CMAKE_CURRENT_SOURCE_DIR}/External_TBBCopy.cmake
    DEPENDEES 
    debug_build
    release_build
)
set(VTK_SMP_IMPLEMENTATION_TYPE TBB)
set(TBB_INCLUDE_DIR ${CMAKE_BINARY_DIR}/TBB/inlcude)
TBB_MALLOC_INCLUDE_DIR:PATH=TBB_MALLOC_INCLUDE_DIR-NOTFOUND
TBB_MALLOC_PROXY_INCLUDE_DIR:PATH=TBB_MALLOC_PROXY_INCLUDE_DIR-NOTFOUND

