if(EXISTS ${PROJECT_SOURCE_DIR}/QvtkUtil/CMakeLists.txt)
    add_subdirectory(QvtkUtil)
else()
    find_package(QvtkUtil REQUIRED)
endif()
add_subdirectory(Data)
add_subdirectory(Filter)
add_subdirectory(InteractorStyle)
add_subdirectory(Viewer)
add_subdirectory(Widget)
add_subdirectory(MainWindow)